### ISSUE TITLE
Getting running

### ISSUE THREAD

**Issue by IMidULti** [txstate-etc/attendance#1]
I do not see instructions on how to use this project from an learning tool. From looking through the router I do see that the URL should be /lti_tool. Is there a way you could add an document describing getting this tool running in something like Sakai?

I got the configuration view to load as a result of manually inserting data into some of the tables, but nothing more.

Thanks in advanced,
Ricky

**Comment by rickyrem** [comment]
I just saw your new readme.md. It might be that my issue is with the version of sakai. I'm anxious to see how the patch changes the implementation.

**Comment by cschauer** [comment]
Hi, Ricky. Assuming you're running both attendance and Sakai on your machine, you could add an External Tool to a site in Sakai and point it at attendance. These are the only required fields:

![External Tool Config]
(http://i.imgur.com/xe6eLFf.png)

Most of the functionality in the tool works without the patch. The only things it adds are the ability to use sites with multiple sections and the ability to set the max points of a grade item to be equal to the number of sessions in the tool.

Unfortunately, roster updates are currently not working in Sakai 10+. We are in the process of migrating to Sakai 10 (also why I've been a bit slow getting documentation up for attendance), so this will get fixed in the next week or two. You can still add the tool as shown above, but the roster won't be loaded. If you just want to get a feel for how the tool works in Sakai, visiting the tool as each of the users in your site will add them to attendance.

Hope this helps. Once I've fixed the bug with roster updates in Sakai 10.4, I'll create the patch for our changes to Sakai and update the documentation. If you happen to be running 2.9, I can give you a patch for that although my plan is to start creating patches for 10+ unless someone specifically requests older patches (we've been using the tool since 2.8).

Chris

**Comment by cschauer** [comment]
I forgot to mention, the following properties will need to be set in your sakai.properties file:

```
sakai.attendance.launch=http://localhost:3000/lti_tool
sakai.attendance.key=yourkey
sakai.attendance.secret=yoursecret

basiclti.outcomes.enabled=true
basiclti.roster.enabled=true
```

**Comment by rickyrem** [comment]
Thank you for your prompt reply and all the details. I am attempting to use this for a school project, and it has to be on Sakai 10.2.

**Comment by cschauer** [comment]
Just want to give an update on this. I've fixed the bug that affected roster updates and will be uploading the patch and updating documentation this weekend (if I get to it) or Monday.
